### PR TITLE
Optimized macOS desktop image

### PR DESCRIPTION
**Pull request by michaelherger**
Here's something that really, really bothered me for a long time 😁: the desktop icon for Material skin used by an "appified" Chrome instance is too big.

Bildschirmfoto 2020-11-22 um 12 16 20

According to [Apple style guides[(https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/) you should have some whitespace (gutter?) around your icon. I'd therefore suggest you replace the existing icon with my copy of it (which I created based on your svg file):

Bildschirmfoto 2020-11-22 um 12 32 37

The first icon is yours, second is my modified version, next to other popular circular icons.

### CODE REVIEW

**Comment by CDrummond** [comment]
Thanks, but the circle is now smaller than safari and chrome. Can you resize so that it is the same? I'd do this myself but I don't have a mac. I think its about 4px (so 2px either side) smaller.

**Comment by michaelherger** [comment]
Wow... is it? I'll give it another try. Damned pixel peeper 😁!

**Comment by CDrummond** [comment]
Yeah, sorry - I can be a real pain in the proverbial!

**Comment by michaelherger** [comment]
Did you actually measure the screenshot, or did you spot this like that?

**Comment by michaelherger** [comment]
Bildschirmfoto 2020-11-22 um 14 27 43

**Comment by CDrummond** [comment]
Looks better now. I did notice that it _looked_ slightly smaller by eye, and then I placed another window over the screenshot to detect the height.

**Pull request merged**
